import 'package:bloc/bloc.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:task_tracker_app/features/home/domain/entities/task_entity.dart';
import 'package:task_tracker_app/features/home/domain/use_cases/create_task_use_case.dart';
import 'package:task_tracker_app/features/home/presentation/bloc/create_task/create_task_event.dart';
import 'package:task_tracker_app/features/home/presentation/bloc/create_task/create_task_state.dart';
import 'package:task_tracker_app/generated/strings.g.dart';

class CreateTaskBloc extends Bloc<CreateTaskEvent, CreateTaskState> {
  final CreateTaskUseCase createTaskUseCase;

  CreateTaskBloc({required this.createTaskUseCase})
      : super(CreateTaskInitial()) {
    on<CreateTaskButtonPressed>(_onCreateTaskButtonPressed);
  }

  Future<void> _onCreateTaskButtonPressed(
      CreateTaskButtonPressed event,
      Emitter<CreateTaskState> emit,
      ) async {
    final validationError = _validateInput(
      title: event.title,
      description: event.description,
      categoryId: event.categoryId,
      priority: event.priority,
      endTime: event.endTime,
    );

    if (validationError != null) {
      emit(CreateTaskValidationError(validationError));
      return;
    }

    final user = FirebaseAuth.instance.currentUser;

    if (user == null) {
      emit(CreateTaskError(t.task.notAuthenticated));
      return;
    }

    final taskEntity = TaskEntity(
      taskId: '', // Will be generated by Firestore
      title: event.title.trim(),
      description: event.description.trim(),
      categoryId: event.categoryId!,
      priority: event.priority!,
      dateTime: event.endTime!,
      endTime: event.endTime!,
      isCompleted: false,
      userId: user.uid,
    );

    emit(CreateTaskLoading());

    try {
      print("Creating task: ${taskEntity.title}");
      print("User ID: ${taskEntity.userId}");

      final newTask = await createTaskUseCase(taskEntity: taskEntity);

      print("Task created successfully: ${newTask.taskId}");

      emit(CreateTaskSuccess(newTask));
    } catch (e) {
      print("Error creating task: $e");
      emit(CreateTaskError("${t.errors.failedToCreateTask} ${e.toString()}"));
    }
  }

  String? _validateInput({
    required String title,
    required String description,
    required String? categoryId,
    required int? priority,
    required DateTime? endTime,
  }) {
    if (title.trim().isEmpty) {
      return t.task.titleRequired;
    }

    if (description.trim().isEmpty) {
      return t.task.descriptionRequired;
    }

    if (categoryId == null) {
      return t.task.selectCategory;
    }

    if (priority == null) {
      return t.task.selectPriorityRequired;
    }

    if (endTime == null) {
      return t.task.selectEndTime;
    }
    return null;
  }
}