import 'package:bloc/bloc.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:task_tracker_app/features/home/domain/entities/task_entity.dart';
import 'package:task_tracker_app/features/home/domain/use_cases/create_task_use_case.dart';
import 'package:task_tracker_app/features/home/presentation/bloc/create_task/create_task_event.dart';
import 'package:task_tracker_app/features/home/presentation/bloc/create_task/create_task_state.dart';

/// ✅ ALL BUSINESS LOGIC IS HERE
/// - Validation
/// - User authentication check
/// - TaskEntity creation
/// - Error handling
/// - Logging
class CreateTaskBloc extends Bloc<CreateTaskEvent, CreateTaskState> {
  final CreateTaskUseCase createTaskUseCase;

  CreateTaskBloc({required this.createTaskUseCase})
      : super(CreateTaskInitial()) {
    on<CreateTaskButtonPressed>(_onCreateTaskButtonPressed);
  }

  Future<void> _onCreateTaskButtonPressed(
      CreateTaskButtonPressed event,
      Emitter<CreateTaskState> emit,
      ) async {
    // ✅ STEP 1: Validate input
    final validationError = _validateInput(
      title: event.title,
      description: event.description,
      categoryId: event.categoryId,
      priority: event.priority,
      endTime: event.endTime,
    );

    if (validationError != null) {
      emit(CreateTaskValidationError(validationError));
      return;
    }

    // ✅ STEP 2: Check user authentication
    final user = FirebaseAuth.instance.currentUser;

    if (user == null) {
      emit(const CreateTaskError("User not authenticated. Please login again."));
      return;
    }

    // ✅ STEP 3: Create task entity
    final taskEntity = TaskEntity(
      taskId: '', // Will be generated by Firestore
      title: event.title.trim(),
      description: event.description.trim(),
      categoryId: event.categoryId!,
      priority: event.priority!,
      dateTime: event.endTime!,
      endTime: event.endTime!,
      isCompleted: false,
      userId: user.uid,
    );

    // ✅ STEP 4: Call use case to create task
    emit(CreateTaskLoading());

    try {
      print("🔄 Creating task: ${taskEntity.title}");
      print("👤 User ID: ${taskEntity.userId}");

      final newTask = await createTaskUseCase(taskEntity: taskEntity);

      print("✅ Task created successfully: ${newTask.taskId}");

      emit(CreateTaskSuccess(newTask));
    } catch (e) {
      print("❌ Error creating task: $e");
      emit(CreateTaskError("Failed to create task: ${e.toString()}"));
    }
  }

  /// ✅ VALIDATION LOGIC
  /// Returns error message if validation fails, null if success
  String? _validateInput({
    required String title,
    required String description,
    required String? categoryId,
    required int? priority,
    required DateTime? endTime,
  }) {
    if (title.trim().isEmpty) {
      return "❌ Task title is required";
    }

    if (description.trim().isEmpty) {
      return "❌ Task description is required";
    }

    if (categoryId == null) {
      return "❌ Please select a category";
    }

    if (priority == null) {
      return "❌ Please select a priority";
    }

    if (endTime == null) {
      return "❌ Please select end time";
    }

    // ✅ All validations passed
    return null;
  }
}