// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKoZlPm3W1tzmeSmieiMUuFhbgNNDE_v8',
    appId: '1:1038502543788:web:903849c5ec5af681527a09',
    messagingSenderId: '1038502543788',
    projectId: 'tasktracker-4743d',
    authDomain: 'tasktracker-4743d.firebaseapp.com',
    storageBucket: 'tasktracker-4743d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_YjalHit4llEoplz-YLbOXj3zHRfintU',
    appId: '1:1038502543788:android:0ef9d1473bb61df9527a09',
    messagingSenderId: '1038502543788',
    projectId: 'tasktracker-4743d',
    storageBucket: 'tasktracker-4743d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Rre7q8-hjxqf7cEEb-2BQ7VfZGwXpjE',
    appId: '1:1038502543788:ios:5039a06dbd63810a527a09',
    messagingSenderId: '1038502543788',
    projectId: 'tasktracker-4743d',
    storageBucket: 'tasktracker-4743d.firebasestorage.app',
    iosBundleId: 'com.example.taskTrackerApp',
  );
}
